### ISSUE TITLE
SDL2 preemptive multithreading

### ISSUE THREAD

**Issue by Cpasjuste** [fgsfdsfgs/ioq3#1]
Hi @fgsfdsfgs , i just implemented preemptive multithreading in SDL2, would it be possible for you to test it to see if there is no issues with it (mainly audio) before pushing it to pacman packages?

Thanks.

[libSDL2.zip](https://github.com/switchports/xash3d-switch/files/2603664/libSDL2.zip)

**Comment by fgsfdsfgs** [comment]
While ioq3 doesn't seem to explicitly use SDL2 threads, the audio appears to work fine in both SDL2 and OpenAL audio backends. I'll test some of my other ports and report back.

**Comment by Cpasjuste** [comment]
Hi @fgsfdsfgs , thanks for the reports. In fact libnx c11 threads does not allow thread priority changes if i'm correct, it works in a preemptive mode (priority is handled by the device if i'm correct again), which should now also be the case for sdl2 threads (audio and custom ones). Can you link me to the revelent code in doom64EX, i guess i should take a closer look too.

**Comment by fgsfdsfgs** [comment]
I guess there hasn't been any issues with this, so whatever.
