### ISSUE TITLE
Crashing...

### ISSUE THREAD

**Issue by lavaJockey** [fgsfdsfgs/ioq3#2]
ioquake3-nx is crashing on the latest commit on Latest Kosmos: https://github.com/AtlasNX/Kosmos/releases/tag/v11.9 Does this have to do with any changes on the new commits?

**Comment by lavaJockey** [comment]
It probably is honestly

**Comment by fgsfdsfgs** [comment]
This is due to the changes introduced in libnx 2.0. Some things probably have to be changed to support that.
